version: '3'

services:
  frontend:
    stdin_open: true
    command:
      - /bin/bash
      - -c
      - |
        npm run dev
    tty: true
    volumes:
      - ./client:/usr/src/app
      - ./client/node_modules:/usr/src/app/node_modules
  nginx:
    volumes:
      - ./nginx/nginx.conf.dev:/etc/nginx/conf.d/nginx.conf
